apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: zerkles/flask-hello-world-wl:first
        ports:
        - containerPort: 8080
