apiVersion: v1
kind: Service
metadata:
  labels:
    app: rooms-rs
  name: rooms-svc-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rooms-rs
